Make script language independent (and fix UZH name issue)
fbuetler/asvz-bot pull request #5
Opened 2021-10-05 20:05 UTC by mathinic

Make UZH to work again and script should now also work on operating systems with different languages, since chrome language in the script is manually set to de_CH. Without the language option, script fails on English operating systems (because SwitchAAI uses different names, e.g. "Universität Zürich" in German but "University of Zurich" in English).

2021-10-09 15:00 UTC, fbuetler requested changes
Apart from the comment above this LGTM.

2021-10-09 15:00 UTC, fbuetler commented on src/asvz_bot.py
> +            ORGANISATIONS[args.organisation], args.username, args.password, args.save_credentials
Upon testing your PR I noticed that my proposed change won't work if the user loads its configuration from the file and not from the CLI arguments. Therefore, this resolution has to be done in the `CredentialsManager` [L82](https://github.com/fbuetler/asvz-bot/pull/5/files#diff-d6802a8b052a193f66a7d9176deedc5d00e753c29f50a6974c3e557007356d17R82) and [L91](https://github.com/fbuetler/asvz-bot/pull/5/files#diff-d6802a8b052a193f66a7d9176deedc5d00e753c29f50a6974c3e557007356d17R91). Sorry for the inconvenience!

2021-10-10 16:01 UTC, mathinic commented on src/asvz_bot.py
> +            ORGANISATIONS[args.organisation], args.username, args.password, args.save_credentials
Changed the dictionary call to L82 and L91 as you proposed. It still works with CLI arguments, however I didn't test it myself with configuration file.

2021-10-10 21:43 UTC, merged

2021-10-10 21:43 UTC, fbuetler commented
Thanks a lot!